export {
  DEFAULT_RANGE_COLOR,
  STORAGE_KEYS,
  SOCKET_TICK_MS,
  WEEKDAY_LABELS,
  TREND_SAMPLE_DATA,
  BRAND_COLOR,
  BRAND_COLOR_ALPHA,
  TREND_Y_MIN,
  TREND_Y_MAX,
  DIALOG_WIDTHS,
  DIALOG_HEIGHTS,
  DIALOG_MAX_HEIGHT,
} from './app.constants';
